services:
  web:
    build: docker/web
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
      - ./docker/config/roslogin-connect.php:/var/www/html/www.reactos.org_config/roslogin-connect.php
      - ./docker/config/testman-connect.php:/var/www/html/www.reactos.org_config/testman-connect.php
      - ./docker/config/gitinfo-connect.php:/var/www/html/www.reactos.org_config/gitinfo-connect.php
    depends_on:
      db:
        condition: service_healthy
      ldap:
        condition: service_started

  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  ldap:
    build:
      context: .
      dockerfile: docker/ldap/Dockerfile
    ports:
      - "389:389"

volumes:
  db_data:
